### ISSUE TITLE
License for the project

### ISSUE THREAD

**Issue by gabber12** [codespaces-io/codespaces#2]
Should we decide on a license for the repo

**Comment by initcron** [comment]
@gabber12 absolutely.  We want to use a liberal license and considering either Apache2 or MIT license. If you have any suggestions, please add.

**Comment by gabber12** [comment]
Though i am not an expert on it i would suggest using MIT License in my opinion its the most permissive one

**Comment by gabber12** [comment]
If going with MIT License [PR](https://github.com/codespaces-io/codespaces/pull/3)

**Comment by initcron** [comment]
added Apache 2 license text.
